aoe2de/aoe2de/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landing.urls')),
    path('leaderboards/', include('leaderboards.urls')),
    path('admin/', admin.site.urls, name='admin_page'),
]

aoe2de/landing/urls.py
from django.urls import path, include

from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.index, name='index'),
    path('leaderboards/', include('leaderboards.urls') ),
    path('about', views.about, name='about'),
    path('resources', views.resources, name='resources'),
    path('contacts', views.contacts, name='contacts')
]

aoe2de/leaderboards/urls.py
from django.urls import path, include

from . import views

app_name = 'leaderboards'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:identifier>/', views.results)
]

aoe2de/base/models.py
from django.db import models

# Create your models here.
class Leaderboard(models.Model):
    game = models.CharField(max_length=100, help_text='AoE2:DE o AoE2:HD')
    leaderboard_id = models.CharField(max_length= 100, help_text='Id type of the leaderboard')
    date = models.DateTimeField(help_text='Collection date')
    csv_table = models.FilePathField(help_text='Path to the CSV file storing the dataset')
    population = models.IntegerField(help_text='Total number of players')
    average_elo = models.FloatField(help_text='Average elo')
    plot = models.TextField(null=True, help_text='Path to the HTML plot of the dataset')
    top_player = models.CharField(null=True, help_text='Top ranking player', max_length=100)

aoe2de/landing/models.py
from django.db import models

# Create your models here.

aoe2de/leaderboards/models.py
from django.db import models

# Create your models here.

aoe2de/base/views.py
from django.shortcuts import render

# Create your views here.

aoe2de/landing/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'landing/index.html', {'nbar': 'home'})

def about(request):
    return render(request, 'landing/about.html', {'nbar': 'about'})

def resources(request):
    return render(request, 'landing/resources.html', {'nbar': 'resources'})

def contacts(request):
    return render(request, 'landing/contact.html', {'nbar': 'contacts'})

aoe2de/leaderboards/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from base.models import Leaderboard
from django.utils import timezone as tz

def index(request):
    return render(request, 'leaderboards/index.html',
                    context={
                    'titles_de': settings.TITLES_DE,
                    'titles_hd': settings.TITLES_HD,
                    'nbar': 'leaderboards'
                    })
def results(request, identifier):
    if identifier.isdigit():
        title = settings.TITLES_DE[int(identifier)]
    else:
        title = settings.TITLES_HD[identifier]
        context = {
                    'title' : title,
                    'nbar': 'leaderboards'
                    }
        return render(request, 'leaderboards/placeholder.html', context = context)


    name = name = '{date}_de_{leaderboard_id}.txt'.format(date=tz.now().strftime('%Y-%m-%d'),
                                    leaderboard_id=identifier)
    query =  Leaderboard.objects.filter(csv_table__contains=name)

    leaderboard = get_object_or_404(query)

    context = {
                'leaderboard' : leaderboard,
                'title' : title,
                'nbar': 'leaderboards'
                }

    return render(request, 'leaderboards/results.html', context = context)

aoe2de/landing/templates/landing/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h1 style="padding-top:25px;">About this site</h1>

<div class="row">
	<div class="col-md-1" style="margin-top: 25px">
	</div>
	<div class="col-md-7" style="margin-top: 25px">
<p>
	This project was made mainly to learn Django as I am a self taught "programmer"; as a result the code is probably a nightmare.
	If you are interested in having a look and improving it, <a href="https://gitlab.com/SlothKing/age2">here</a> you can find the GitLab repo.
</p>
			</div>
	<div class="col-md-1">

	</div>
		<div class="col-md--3">
			<h3>Redddit Magic</h3>
			{% autoescape off %}
				<script src='https://redditjs.com/subreddit.js' data-subreddit='aoe2', data-subreddit-mode='grid'></script>
			{% endautoescape %}
		</div>
</div>
{% endblock content %}

aoe2de/landing/templates/landing/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
contacts
{% endblock content %}

aoe2de/landing/templates/landing/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex justify-cntent-center align-items-center">
  <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">

    <!-- Slide 1 -->
    <div class="carousel-item active">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Welcome to Age of Empires 2: Data Edition!</h2>
        <p class="animate__animated animate__fadeInUp">
          This is project to gather resources from the Age of Empires 2 community.
          Explore the website and have fun!
        </p>
        <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read more</a>
      </div>
    </div>

    <!-- Slide 2 -->
    <div class="carousel-item">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Leaderboards</h2>
        <p class="animate__animated animate__fadeInUp">Here you can find the daily Elo distrubution in the ranked modes of both DE and Voobly.</p>
        <a href="{% url 'leaderboards:index' %}" class="btn-get-started animate__animated animate__fadeInUp">Go to leaderboards</a>
      </div>
    </div>

    <!-- Slide 3 -->
    <div class="carousel-item">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Sources</h2>
        <p class="animate__animated animate__fadeInUp">All the data is collected thorugh the wonderful APIs of <b>AoE2.net</b>. Have a look at their website:</p>
        <a href="https://www.aoe2.net" class="btn-get-started animate__animated animate__fadeInUp">Go there!</a>
      </div>
    </div>

    <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>
</section><!-- End Hero -->
<!-- <div class="container-fluid" style="margin-top: 25px">
  <div class="row">
    <div class="col-md-8">
      <div>
        <p>Welcome to Age of Empires 2: Data Edition!</p>

        This is a small project to collect resources from the Age of Empires 2 community!

        The site contains:
        <ul>
          <li><a href="{% url 'leaderboards:index' %}">Elo distribution</a> of all the leaderboards from both DE and HD (the latter is yet to implement)</li>
          <li>Other stuff yet to implement</li>
        </ul>
      </div>
    </div>
 -->
  </div>

</div>
{% endblock %}

aoe2de/landing/templates/landing/resources.html
{% extends "base.html" %}
{% load static %}

aoe2de/leaderboards/templates/leaderboards/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid" style="padding-top: 20px; padding-bottom: 20px;">

  <div class="row d-flex" >
    <div class="col-md-2">

    </div>
    <div class="col-md-4" style="padding-left: 20px" >
      <h1 style="padding-bottom: 10px"><u>Definitive Edition</u></h1>
           <ul class="no-bullets" style="text-align: center">
             {% for index, text in titles_de.items %}
             <li class="special"><a class="special" href="{{ index }}">{{ text }}</a></li>
             {% endfor %}
           </ul>
      </div>
    <div class="col-md-4" style="padding-left: 20px">
      <h1 style="padding-bottom: 10px"><u>Voobly</u></h1>
           <ul class="no-bullets" style="text-align: center">
             {% for index, text in titles_hd.items %}
             <li class="special"><a class="special" href="{{ index }}">{{ text }}</a></li>
             {% endfor %}
           </ul>
    </div>
  </div>
</div>
{% endblock content %}

aoe2de/leaderboards/templates/leaderboards/placeholder.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<h1>YET TO IMPLEMENT</h1>

{% endblock content %}

aoe2de/leaderboards/templates/leaderboards/results.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12" style="text-align: center; padding-top: 20px;">
      <h1>{{ title }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      The plot is interactive! <br>
      It counts the number of players (y axis) at a certain Elo (x axis, grouped with a bin of 5 points)
    </div>
    <div class="col-sm-6">
      <ul>
         <li>Number of players: {{ leaderboard.population }}</li>
         <li>Average Elo: {{ leaderboard.average_elo|floatformat:2 }}</li>
         <li>Top player: {{ leaderboard.top_player }}</li>
       </ul>
    </div>
  </div>
</div>


  {% autoescape off %}
  {{ leaderboard.plot }}
  {% endautoescape %}

  <p>Last update (Europe/Rome): {{ leaderboard.date }} </p>
{% endblock content %}

aoe2de/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

  {% block style %}

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'style0.css' %}" rel="stylesheet">

  {% endblock style %}

  <title>{% block page_title %}AoE2: Data Edition{% endblock page_title %}</title>
  {% block script_engine %}

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% endblock script_engine %}
  {% block header %}{% endblock header %}
</head>

    <body>
    {% block section_title %}
    {% endblock section_title %}

    {% block navigation %}
    {% include "navigation.html" %}
    {% endblock navigation %}

    <main id='main' class="content" style="padding-bottom: 20px">
      {% block content %}
      {% endblock content %}
    </main>

    {% block footer %}
    {% include "footer.html" %}
    {% endblock footer %}

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>


</body>
</html>

aoe2de/templates/footer.html
<footer class="footer" id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
	<div class="footer-top">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
						<p>This site is not affiliated with or endorsed by Microsoft Corporation.
							Age of Empires II: HD and Age of Empires II: Definitive Edition are
							trademarks or registered trademarks of Microsoft Corporation in the
							U.S. and other countries.</p>
				</div>
			</div>
			<div class="row" style="padding-top:20px;">
				<div class="col-lg-4 col-md-6 footer-links">
					<h4>Useful Links</h4>
					<ul>
						<li><i class="bx bx-chevron-right"></i> <a href="{% url 'landing:index' %}">Home</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="{% url 'landing:about' %}">About us</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="{% url 'landing:resources' %}">Resources</a></li>
					</ul>
				</div>
<!--
				<div class="col-lg-3 col-md-6 footer-links">
					<h4>Our Services</h4>
					<ul>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
					</ul>
				</div> -->

				<div class="col-lg-4 col-md-6 footer-contact">
					<h4>Contact Us</h4>
					<p>
						<strong>Email:</strong> slothking95@protonmail.com<br>
					</p>

				</div>

				<div class="col-lg-4 col-md-6 footer-info">
					<h3>Disclaimer</h3>
					This is a passon project: learn more <a href="{% url "landing:about" %}">here!</a>
					<div class="social-links mt-3">
						<a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
						<a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
						<a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
						<a href="#" class="linkedin"><i class="bx bxl-reddit"></i></a>
					</div>
				</div>

			</div>
		</div>
	</div>

	<div class="container">
		<div class="copyright">
			&copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
		</div>
		<div class="credits">
			<!-- All the links in the footer should remain intact. -->
			<!-- You can delete the links only if you purchased the pro version. -->
			<!-- Licensing information: https://bootstrapmade.com/license/ -->
			<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
			Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
		</div>
	</div>
</footer>

aoe2de/templates/navigation.html
<!-- <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
  <a class="navbar-brand" href="{% url 'landing:index' %}"><i class="fas fa-home"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:index' %}">Leaderboards</a>
      </li>
    </ul>
  </div>
</nav> -->
{% load static %}

<header id="header" class="fixed-top header">
  <div class="container">

    <div class="logo float-left">


    <nav class="nav-menu float-right d-none d-lg-block">
      <ul>
        <li class="active"><a href="{% url 'landing:index' %}">Home</a></li>
        <li><a href="{% url 'leaderboards:index' %}">Leaderboards</a></li>
        <li><a href="{% url 'landing:about' %}">About</a></li>
        <li><a href="{% url 'landing:resources' %}">Resources</a></li>
        <li><a href="team.html">Team</a></li>
        <li><a href="blog.html">Blog</a></li>
        <li class="drop-down"><a href="">Drop Down</a>
          <ul>
            <li><a href="#">Drop Down 1</a></li>
            <li class="drop-down"><a href="#">Drop Down 2</a>
              <ul>
                <li><a href="#">Deep Drop Down 1</a></li>
                <li><a href="#">Deep Drop Down 2</a></li>
                <li><a href="#">Deep Drop Down 3</a></li>
                <li><a href="#">Deep Drop Down 4</a></li>
                <li><a href="#">Deep Drop Down 5</a></li>
              </ul>
            </li>
            <li><a href="#">Drop Down 3</a></li>
            <li><a href="#">Drop Down 4</a></li>
            <li><a href="#">Drop Down 5</a></li>
          </ul>
        </li>
        <li><a href="{% url 'landing:'}">Contact Us</a></li>
      </ul>
    </nav><!-- .nav-menu -->

  </div>
</header><!-- End Header -->


<button type="button" class="mobile-nav-toggle d-lg-none"><i class="bx bx-menu"></i></button>

<header id="header" class="fixed-top ">
  <div class="container">
    <div class="logo float-left">
    {% if nbar == 'home' %}
    <h1 class="text-light" style="font-variant: small-caps;"><a href="{% url 'landing:index' %}"><span>AoE2:Data Edition</span></a></h1>
    {% else %}
    <a href="{% url 'landing:index' %}"><img src="{% static 'images/favicon.png'%}" alt="" class="img-fluid"></a>
    {% endif %}
    </div>
    <nav class="nav-menu float-right d-none d-lg-block">
      <ul>
        <li class="{% if nbar == 'home' %}active{% endif %}"><a href="{% url 'landing:index' %}">Home</a></li>
        <li class="{% if nbar == 'leaderboards' %}active{% endif %}"><a href="{% url 'leaderboards:index' %}">Leaderboards</a></li>
        <li class="{% if nbar == 'about' %}active{% endif %}"><a href="{% url 'landing:about' %}">About</a></li>
        <li class="{% if nbar == 'resources' %}active{% endif %}"><a href="{% url 'landing:resources' %}">Resources</a></li>
        <li><a href="team.html">Team</a></li>
        <li><a href="blog.html">Blog</a></li>
        <li class="drop-down"><a href="">Drop Down</a>
          <ul>
            <li><a href="#">Drop Down 1</a></li>
            <li class="drop-down"><a href="#">Drop Down 2</a>
              <ul>
                <li><a href="#">Deep Drop Down 1</a></li>
                <li><a href="#">Deep Drop Down 2</a></li>
                <li><a href="#">Deep Drop Down 3</a></li>
                <li><a href="#">Deep Drop Down 4</a></li>
                <li><a href="#">Deep Drop Down 5</a></li>
              </ul>
            </li>
            <li><a href="#">Drop Down 3</a></li>
            <li><a href="#">Drop Down 4</a></li>
            <li><a href="#">Drop Down 5</a></li>
          </ul>
        </li>
        <li><a href="contact.html">Contact Us</a></li>
      </ul>
    </nav><!-- .nav-menu -->

  </div>
</header><!-- End Header -->